### ISSUE TITLE
QR Code not showing 

### ISSUE THREAD

**Issue by ndc168** [sn4k3/Aliexpress-Tracking-QRBarcode#1]
No QR code under https://track.aliexpress.com/logisticsdetail.htm

Possibily due to site changing?

Very useful code, pls consider update, thanks!!

**Comment by sn4k3** [comment]
You are right. I didn't notice that since i never use that page.
I will update soon. Please wait util i close this request.
Thank you for your input

**Comment by sn4k3** [comment]
Fixed with new version
