### ISSUE TITLE
Compatibility w/ Userscript+ : Show Site All UserJS

### ISSUE THREAD

**Issue by ndc168** [sn4k3/Aliexpress-Tracking-QRBarcode#2]
QR code would not show when "Userscript+ : Show Site All UserJS" enabled in Tamper Moneky under Chromex64.

Pls consider conflict avoidance feature in code, as that module had 20,000 installation base and still active.

Thank you for your efforts!!

**Comment by sn4k3** [comment]
Hello, i have installed that script, however everything work with me. Can you see if theres other script? Or maybe send console log? 
Regards
